spring:
  application:
    name: community-server
server:
  port: 8080
jwt:
  sign: EPV1usya147KOa66sqXHnvs8T4l89owm
  secret: 0sq4dVZ+nW8ruyRNiXhZkEwvkUKZXPSBMgQUw5YfCib1Ml/FikDrd2wZHEvM3ibhMZcMp/y4wqpGccuJ/uVOJg==
  expiration: 86400000

--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345


--- #---------------------中间件配置---------------------------
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
